name: Create new version tag

on:
  push:
    branches: [main]

jobs:
  create-new-version-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Create new version tag
        uses: gradle/gradle-build-action@v2
        with:
          arguments: createSemverTag -Psemver.stage=auto

      - name: Push Tag
        run: git push --follow-tags